#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=9.4.5
PACKAGE_DEPEND=(readline openssl)

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.bz2

botbrew_do_build() {
	botbrew_download ftp://ftp.postgresql.org/pub/source/v${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
	botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
	botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
	botbrew_patchtree -p1 ${G_SOURCE} patch/${FULLNAME}-android.patch
	botbrew_import
  
	if ! [ -e ${G_OBJECT}/Makefile ]; then
    (
      mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
      CPPFLAGS="-I${G_INCDIR}" CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}" \
      LDFLAGS="-L${G_LIBDIR}" USE_UNNAMED_POSIX_SEMAPHORES="1" \
      ac_cv_func_random=yes ac_cv_func_srandom=yes \
      ../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
      --disable-rpath --without-tcl --without-perl --without-python \
      --without-pam --without-ldap --with-openssl --disable-thread-safety \
      --with-system-tzdata=/system/usr/share/zoneinfo/
    )
  fi
  if ! [ -e ${G_EXPORT}/.d ]; then
    ${G_MAKE} -C ${G_OBJECT}
    ${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
    ${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* || true
    touch ${G_EXPORT}/.d
  fi
}
