#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=7.47.1
PACKAGE_DEPEND=( openssl )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_NAME}-${PACKAGE_VERSION//./_}
ARCHIVE=${PACKAGE_NAME}-${PACKAGE_VERSION//./_}.tar.gz

botbrew_do_build() {
  botbrew_download https://github.com/curl/curl/archive/${ARCHIVE} ${ARCHIVE}
  botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
  botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
  
	botbrew_import
	if ! [ -e ${G_SOURCE}/configure ]; then
		(cd ${G_SOURCE}; ./buildconf)
	fi
	if ! [ -e ${G_OBJECT}/Makefile ]; then
		(
			mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
			CPPFLAGS="-I${G_INCDIR}" CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}" \
			LDFLAGS="-L${G_LIBDIR} -Wl,-rpath-link,${G_LIBDIR}" \
			../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
				--enable-threaded-resolver --with-ssl --with-ca-path=${G_INSTALLPREFIX}/etc/ssl/certs
		)
	fi
	if ! [ -e ${G_EXPORT}/.d ]; then
		${G_MAKE} -C ${G_OBJECT}
		${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
		${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* ${G_EXP_LIBDIR}/*.so* || true
		botbrew_fix_interpreter_path ${G_EXPORT}
		touch ${G_EXPORT}/.d
	fi
}

