#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.0
PACKAGE_DEPEND=( libcsploit-common libcares libpcap )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
  botbrew_download https://github.com/cSploit/${PACKAGE_NAME}/releases/download/v${PACKAGE_VERSION}/${ARCHIVE} ${ARCHIVE}
  botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
  botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
  botbrew_import
  if ! [ -e ${G_OBJECT}/Makefile ]; then
    (
      mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
      CPPFLAGS="-I${G_INCDIR}" CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}" \
      LDFLAGS="-L${G_LIBDIR}" ac_cv_func_malloc_0_nonnull=yes \
      ../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET}
    )
  fi
  if ! [ -e ${G_EXPORT}/.d ]; then
    ${G_MAKE} -C ${G_OBJECT}
    ${G_MAKE} -C ${G_OBJECT} install DESTDIR=$(pwd)/${G_EXPORT}
    ${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* || true
    touch ${G_EXPORT}/.d
  fi
}
