#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.0
PACKAGE_DEPEND=()

botbrew_do_build() {
  botbrew_git git://github.com/morristech/android-ifaddrs.git ${PACKAGE_NAME}
  botbrew_copytree ${PACKAGE_NAME} ${G_SOURCE} || true
  if ! [ -e ${G_OBJECT}/.d ]; then
    (
      mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
      ${G_CC} ${G_CPPFLAGS} ${G_ALL_CFLAGS} -c -O2 -o ifaddrs.o ../${G_SOURCE}/ifaddrs.c
      ${G_CC} ${G_CPPFLAGS} ${G_ALL_CFLAGS} -shared -O2 -o libifaddrs.so ifaddrs.o
      ${G_AR} -r libifaddrs.a ifaddrs.o
      touch .d
    )
  fi
  if ! [ -e ${G_EXPORT}/.d ]; then
    mkdir -p ${G_EXP_LIBDIR}
    mkdir -p ${G_EXP_INCDIR}
    install ${G_OBJECT}/libifaddrs.so ${G_OBJECT}/libifaddrs.a ${G_EXP_LIBDIR}/
    install -m 644 ${G_SOURCE}/ifaddrs.h ${G_EXP_INCDIR}/
    ${G_STRIP} --strip-unneeded ${G_EXP_LIBDIR}/*.so* || true
    touch ${G_EXPORT}/.d
  fi
}
