#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=0.6
PACKAGE_DEPEND=( libnet )

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar

botbrew_do_build() {
  botbrew_download http://arpoison.sourceforge.net/${ARCHIVE}.gz ${ARCHIVE}
  botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
  botbrew_copytree ${FULLNAME}/${PACKAGE_NAME} ${G_SOURCE} || true
  botbrew_import
  botbrew_fix_crosslibconfig ${G_SYSDIR}/bin/libnet-config
  if ! [ -e ${G_OBJECT}/${PACKAGE_NAME} ]; then
    mkdir -p ${G_OBJECT} || true
    libnet_defines=$(${G_SYSDIR}/bin/libnet-config --defines)
    libnet_libs=$(${G_SYSDIR}/bin/libnet-config --libs)
    CPPFLAGS="-I${G_INCDIR} -I${G_SOURCE} $libnet_defines"
    CFLAGS="${G_CPPFLAGS} ${G_ALL_CFLAGS}"
    LDFLAGS="-L${G_LIBDIR} $libnet_libs"
    ${G_CC} ${CFLAGS} ${CPPFLAGS} ${G_SOURCE}/${PACKAGE_NAME}.c \
    -o ${G_OBJECT}/${PACKAGE_NAME} ${LDFLAGS}
  fi
  if ! [ -e ${G_EXPORT}/.d ]; then
    mkdir -p ${G_EXP_BINDIR}
    cp ${G_OBJECT}/${PACKAGE_NAME} ${G_EXP_BINDIR}/
    ${G_STRIP} --strip-unneeded ${G_EXP_BINDIR}/* || true
    touch ${G_EXPORT}/.d
  fi
}
