#!/bin/bash
if [ "${G_BOTBREW}" = "" ]; then kill -SIGINT $$; fi

PACKAGE_NAME=$(basename $(pwd))
PACKAGE_VERSION=1.24
PACKAGE_DEPEND=(libnet libpcap)

FULLNAME=${PACKAGE_NAME}-${PACKAGE_VERSION}
ARCHIVE=${FULLNAME}.tar.gz

botbrew_do_build() {
  botbrew_download https://sourceforge.net/projects/${PACKAGE_NAME}/files/${PACKAGE_NAME}/${PACKAGE_VERSION}/${ARCHIVE}/download ${ARCHIVE}
  botbrew_unpack ${ARCHIVE} ${FULLNAME} || true
  botbrew_copytree ${FULLNAME}/${FULLNAME} ${G_SOURCE} || true
  botbrew_patchtree -p1 ${G_SOURCE} patch/${FULLNAME}-android.patch
  botbrew_fix_config ${G_SOURCE}
  botbrew_import
  botbrew_fix_crosslibconfig ${G_BINDIR}/libnet-config
  botbrew_fix_crosslibconfig ${G_BINDIR}/pcap-config
  if ! [ -e ${G_OBJECT}/Makefile ]; then
    (
      mkdir -p ${G_OBJECT}; cd ${G_OBJECT}
      CPPFLAGS="-I${G_INCDIR} -D__FAVOR_BSD" LDFLAGS="-L${G_LIBDIR}" \
      CFLAGS="${G_CPPFLAGS} -I${G_INCDIR} ${G_ALL_CFLAGS}" \
      ../${G_SOURCE}/configure ${G_SYSTEMPREFIX[@]} --host=${G_TRIPLET} \
        --disable-libglib --with-libpcap=yes
    )
  fi
  if ! [ -e ${G_EXPORT}/.d ]; then
    ${G_MAKE} -C ${G_OBJECT} shared static
    
    ${G_MAKE} -C ${G_OBJECT} -j1 _installshared INSTALL_PREFIX=$(pwd)/${G_EXPORT}
    
    ${G_STRIP} --strip-unneeded ${G_EXP_LIBDIR}/*.so.* || true
    touch ${G_EXPORT}/.d
  fi
}
